# Generated by Django 6.0 on 2026-01-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('published', 'Published'), ('blocked', 'Blocked')], default='moderator', max_length=120),
        ),
    ]
